# Mendefinisikan langkah-langkah atau proses yang akan dilakukan oleh Google Cloud Build.
steps:
  # Mendefinisikan langkah pertama, yaitu menggunakan image docker yang disediakan oleh Google Cloud Build.
  - name: "gcr.io/cloud-builders/docker"
    # Mendefinisikan argumen yang akan digunakan pada langkah pertama,
    # yaitu melakukan build Docker image dengan tag gcr.io/$PROJECT_ID/app-user:1.0.
    args: ["build", "-t", "gcr.io/$PROJECT_ID/app-user:1.0", "."]

  # Mendefinisikan langkah kedua, yaitu menggunakan image docker yang disediakan oleh Google Cloud Build.
  - name: "gcr.io/cloud-builders/docker"
    # Mendefinisikan argumen yang akan digunakan pada langkah kedua,
    # yaitu melakukan push Docker image yang telah dibuild ke Google Container Registry
    # dengan tag gcr.io/$PROJECT_ID/app-user:1.0.
    args: ["push", "gcr.io/$PROJECT_ID/app-user:1.0"]

  # Mendefinisikan langkah ketiga, yaitu menggunakan image gcloud yang disediakan oleh Google Cloud Build.
  - name: "gcr.io/cloud-builders/gcloud"
    #  Mendefinisikan argumen yang akan digunakan pada langkah ketiga,
    # yaitu melakukan deploy aplikasi ke Google app-user Engine dengan
    # menggunakan image Docker yang telah dibuild dan dipush ke Google Container Registry
    # dengan tag gcr.io/$PROJECT_ID/app-user:1.0.
    args:
      [
        "app",
        "deploy",
        "--image-url=gcr.io/$PROJECT_ID/app-user:1.0",
        "--project=$PROJECT_ID",
        "--quiet",
        "--promote",
      ]
